### ISSUE TITLE
README example does not work

### ISSUE THREAD

**Issue by schmurfy** [celluloid/celluloid-dns#3]
on my machine (OS X 10.8) the server just hangs when a request is received, I think it just get stuck on "@block.call" which never calls the block but never returns either (just tested with a quick puts debugging ;) ).

is it supposed to work ?

I tested it with latest celluloid release (0.14.1) and I tested both latest celluloid-dns release and master with the same result :(

**Comment by Hermanverschooten** [comment]
I am having the same problem on OSX Yosemite, with both MRI 2.2.0 and RBX 2.2.10. I tried with master, but that makes no difference.

**Comment by tarcieri** [comment]
Celluloid::DNS is defunct. Please use RubyDNS:

https://github.com/ioquatix/rubydns
