### ISSUE TITLE
Please update gem at rubygems.org

### ISSUE THREAD

**Issue by martin-schmidt** [celluloid/celluloid-dns#8]
The [latest version available at rubygems.org](https://rubygems.org/gems/celluloid-dns) is 0.0.1. Because rubygems.org is the default gem source `gem install celluloid-dns` installs a non working gem for almost everybody:

    $ gem install celluloid-dns
    Successfully installed celluloid-dns-0.0.1
    Parsing documentation for celluloid-dns-0.0.1
    Installing ri documentation for celluloid-dns-0.0.1
    Done installing documentation for celluloid-dns after 0 seconds
    1 gem installed

**Comment by ioquatix** [comment]
This gem isn't really officially released. But, I guess we could do something about that?

**Comment by severin** [comment]
:+1:

**Comment by digitalextremist** [comment]
@ioquatix does the repository reflect a releasable gem now?

**Comment by ioquatix** [comment]
Yes pretty much but I really need to do a bit more testing.

**Comment by ioquatix** [comment]
Are you guys keen for a release?

**Comment by tarcieri** [comment]
Sure

**Comment by ioquatix** [comment]
I don't have permission to push this gem :/

```
rake release
celluloid-dns 0.17.3 built to pkg/celluloid-dns-0.17.3.gem.
Tagged v0.17.3.
Pushed git commits and tags.
rake aborted!
Pushing gem to https://rubygems.org...
You do not have permission to push to this gem.
/home/samuel/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/gem_helper.rb:170:in `sh'
/home/samuel/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/gem_helper.rb:101:in `rubygem_push'
/home/samuel/.rvm/gems/ruby-2.3.0/gems/bundler-1.11.2/lib/bundler/gem_helper.rb:67:in `block in install'
Tasks: TOP => release => release:rubygem_push
(See full trace by running task with --trace)

```

**Comment by digitalextremist** [comment]
As long as the code in master is current, I can push it today.

**Comment by tarcieri** [comment]
@digitalextremist go for it (also we should give @ioquatix gem access)

**Comment by ioquatix** [comment]
Yes please do make a release from current master, it's already tagged.

**Comment by digitalextremist** [comment]
Right on -- will cut this in a few hours.

**Comment by digitalextremist** [comment]
@tarcieri I actually don't have access either. I just tried to push it.

**Comment by tarcieri** [comment]
@ioquatix @digitalextremist can you both email me privately and tell me what email addresses you'd like me to use to grant you access to this gem?

Unfortunately rubygems.org makes granting this sort of access way too hard.

**Comment by digitalextremist** [comment]
Sent //

**Comment by tarcieri** [comment]
You both should have push access now

**Comment by ioquatix** [comment]
Okay, I will manage the release then.

**Comment by digitalextremist** [comment]
Trouble @ioquatix?

**Comment by ioquatix** [comment]
Okay we released it.
